spring:
  application:
    name: springboot-generate

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis-plus.mapper-locations: classpath:/mapper/*Mapper.xml
mybatis-plus.typeAliasesPackage: com.lind.springboot.mybtisplugs.entity
