spring:
  application:
    name: xboot-test

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update #有变更时自动建立表
#mybatis plus 设置
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackage: cn.exrick.xboot.your.entity.**,cn.exrick.xboot.core.entity.**

---
spring:
  profiles: test
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
