package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActApproveAgent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.agent_id
     *
     * @mbg.generated
     */
    private String agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.authorizer_id
     *
     * @mbg.generated
     */
    private String authorizerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.agent_term
     *
     * @mbg.generated
     */
    private Integer agentTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.agent_start_time
     *
     * @mbg.generated
     */
    private Date agentStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.agent_end_time
     *
     * @mbg.generated
     */
    private Date agentEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.create_department_id
     *
     * @mbg.generated
     */
    private String createDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.create_department_ids
     *
     * @mbg.generated
     */
    private String createDepartmentIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.update_department_id
     *
     * @mbg.generated
     */
    private String updateDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_approve_agent.update_department_ids
     *
     * @mbg.generated
     */
    private String updateDepartmentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_approve_agent
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.id
     *
     * @return the value of act_approve_agent.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.id
     *
     * @param id the value for act_approve_agent.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.agent_id
     *
     * @return the value of act_approve_agent.agent_id
     *
     * @mbg.generated
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.agent_id
     *
     * @param agentId the value for act_approve_agent.agent_id
     *
     * @mbg.generated
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.authorizer_id
     *
     * @return the value of act_approve_agent.authorizer_id
     *
     * @mbg.generated
     */
    public String getAuthorizerId() {
        return authorizerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.authorizer_id
     *
     * @param authorizerId the value for act_approve_agent.authorizer_id
     *
     * @mbg.generated
     */
    public void setAuthorizerId(String authorizerId) {
        this.authorizerId = authorizerId == null ? null : authorizerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.agent_term
     *
     * @return the value of act_approve_agent.agent_term
     *
     * @mbg.generated
     */
    public Integer getAgentTerm() {
        return agentTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.agent_term
     *
     * @param agentTerm the value for act_approve_agent.agent_term
     *
     * @mbg.generated
     */
    public void setAgentTerm(Integer agentTerm) {
        this.agentTerm = agentTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.agent_start_time
     *
     * @return the value of act_approve_agent.agent_start_time
     *
     * @mbg.generated
     */
    public Date getAgentStartTime() {
        return agentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.agent_start_time
     *
     * @param agentStartTime the value for act_approve_agent.agent_start_time
     *
     * @mbg.generated
     */
    public void setAgentStartTime(Date agentStartTime) {
        this.agentStartTime = agentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.agent_end_time
     *
     * @return the value of act_approve_agent.agent_end_time
     *
     * @mbg.generated
     */
    public Date getAgentEndTime() {
        return agentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.agent_end_time
     *
     * @param agentEndTime the value for act_approve_agent.agent_end_time
     *
     * @mbg.generated
     */
    public void setAgentEndTime(Date agentEndTime) {
        this.agentEndTime = agentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.status
     *
     * @return the value of act_approve_agent.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.status
     *
     * @param status the value for act_approve_agent.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.create_time
     *
     * @return the value of act_approve_agent.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.create_time
     *
     * @param createTime the value for act_approve_agent.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.create_by
     *
     * @return the value of act_approve_agent.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.create_by
     *
     * @param createBy the value for act_approve_agent.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.update_time
     *
     * @return the value of act_approve_agent.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.update_time
     *
     * @param updateTime the value for act_approve_agent.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.update_by
     *
     * @return the value of act_approve_agent.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.update_by
     *
     * @param updateBy the value for act_approve_agent.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.del_flag
     *
     * @return the value of act_approve_agent.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.del_flag
     *
     * @param delFlag the value for act_approve_agent.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.create_department_id
     *
     * @return the value of act_approve_agent.create_department_id
     *
     * @mbg.generated
     */
    public String getCreateDepartmentId() {
        return createDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.create_department_id
     *
     * @param createDepartmentId the value for act_approve_agent.create_department_id
     *
     * @mbg.generated
     */
    public void setCreateDepartmentId(String createDepartmentId) {
        this.createDepartmentId = createDepartmentId == null ? null : createDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.tenant_id
     *
     * @return the value of act_approve_agent.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.tenant_id
     *
     * @param tenantId the value for act_approve_agent.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.create_department_ids
     *
     * @return the value of act_approve_agent.create_department_ids
     *
     * @mbg.generated
     */
    public String getCreateDepartmentIds() {
        return createDepartmentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.create_department_ids
     *
     * @param createDepartmentIds the value for act_approve_agent.create_department_ids
     *
     * @mbg.generated
     */
    public void setCreateDepartmentIds(String createDepartmentIds) {
        this.createDepartmentIds = createDepartmentIds == null ? null : createDepartmentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.update_department_id
     *
     * @return the value of act_approve_agent.update_department_id
     *
     * @mbg.generated
     */
    public String getUpdateDepartmentId() {
        return updateDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.update_department_id
     *
     * @param updateDepartmentId the value for act_approve_agent.update_department_id
     *
     * @mbg.generated
     */
    public void setUpdateDepartmentId(String updateDepartmentId) {
        this.updateDepartmentId = updateDepartmentId == null ? null : updateDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_approve_agent.update_department_ids
     *
     * @return the value of act_approve_agent.update_department_ids
     *
     * @mbg.generated
     */
    public String getUpdateDepartmentIds() {
        return updateDepartmentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_approve_agent.update_department_ids
     *
     * @param updateDepartmentIds the value for act_approve_agent.update_department_ids
     *
     * @mbg.generated
     */
    public void setUpdateDepartmentIds(String updateDepartmentIds) {
        this.updateDepartmentIds = updateDepartmentIds == null ? null : updateDepartmentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_approve_agent
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", agentId=").append(agentId);
        sb.append(", authorizerId=").append(authorizerId);
        sb.append(", agentTerm=").append(agentTerm);
        sb.append(", agentStartTime=").append(agentStartTime);
        sb.append(", agentEndTime=").append(agentEndTime);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createDepartmentId=").append(createDepartmentId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", createDepartmentIds=").append(createDepartmentIds);
        sb.append(", updateDepartmentId=").append(updateDepartmentId);
        sb.append(", updateDepartmentIds=").append(updateDepartmentIds);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}