package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActEvtLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.LOG_NR_
     *
     * @mbg.generated
     */
    private Long logNr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.TYPE_
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.PROC_INST_ID_
     *
     * @mbg.generated
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.EXECUTION_ID_
     *
     * @mbg.generated
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.TASK_ID_
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.TIME_STAMP_
     *
     * @mbg.generated
     */
    private Date timeStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.USER_ID_
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.LOCK_OWNER_
     *
     * @mbg.generated
     */
    private String lockOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.LOCK_TIME_
     *
     * @mbg.generated
     */
    private Date lockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.IS_PROCESSED_
     *
     * @mbg.generated
     */
    private Byte isProcessed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_evt_log.DATA_
     *
     * @mbg.generated
     */
    private byte[] data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_evt_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.LOG_NR_
     *
     * @return the value of act_evt_log.LOG_NR_
     *
     * @mbg.generated
     */
    public Long getLogNr() {
        return logNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.LOG_NR_
     *
     * @param logNr the value for act_evt_log.LOG_NR_
     *
     * @mbg.generated
     */
    public void setLogNr(Long logNr) {
        this.logNr = logNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.TYPE_
     *
     * @return the value of act_evt_log.TYPE_
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.TYPE_
     *
     * @param type the value for act_evt_log.TYPE_
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.PROC_DEF_ID_
     *
     * @return the value of act_evt_log.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.PROC_DEF_ID_
     *
     * @param procDefId the value for act_evt_log.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.PROC_INST_ID_
     *
     * @return the value of act_evt_log.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.PROC_INST_ID_
     *
     * @param procInstId the value for act_evt_log.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.EXECUTION_ID_
     *
     * @return the value of act_evt_log.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.EXECUTION_ID_
     *
     * @param executionId the value for act_evt_log.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.TASK_ID_
     *
     * @return the value of act_evt_log.TASK_ID_
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.TASK_ID_
     *
     * @param taskId the value for act_evt_log.TASK_ID_
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.TIME_STAMP_
     *
     * @return the value of act_evt_log.TIME_STAMP_
     *
     * @mbg.generated
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.TIME_STAMP_
     *
     * @param timeStamp the value for act_evt_log.TIME_STAMP_
     *
     * @mbg.generated
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.USER_ID_
     *
     * @return the value of act_evt_log.USER_ID_
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.USER_ID_
     *
     * @param userId the value for act_evt_log.USER_ID_
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.LOCK_OWNER_
     *
     * @return the value of act_evt_log.LOCK_OWNER_
     *
     * @mbg.generated
     */
    public String getLockOwner() {
        return lockOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.LOCK_OWNER_
     *
     * @param lockOwner the value for act_evt_log.LOCK_OWNER_
     *
     * @mbg.generated
     */
    public void setLockOwner(String lockOwner) {
        this.lockOwner = lockOwner == null ? null : lockOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.LOCK_TIME_
     *
     * @return the value of act_evt_log.LOCK_TIME_
     *
     * @mbg.generated
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.LOCK_TIME_
     *
     * @param lockTime the value for act_evt_log.LOCK_TIME_
     *
     * @mbg.generated
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.IS_PROCESSED_
     *
     * @return the value of act_evt_log.IS_PROCESSED_
     *
     * @mbg.generated
     */
    public Byte getIsProcessed() {
        return isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.IS_PROCESSED_
     *
     * @param isProcessed the value for act_evt_log.IS_PROCESSED_
     *
     * @mbg.generated
     */
    public void setIsProcessed(Byte isProcessed) {
        this.isProcessed = isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_evt_log.DATA_
     *
     * @return the value of act_evt_log.DATA_
     *
     * @mbg.generated
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_evt_log.DATA_
     *
     * @param data the value for act_evt_log.DATA_
     *
     * @mbg.generated
     */
    public void setData(byte[] data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logNr=").append(logNr);
        sb.append(", type=").append(type);
        sb.append(", procDefId=").append(procDefId);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", executionId=").append(executionId);
        sb.append(", taskId=").append(taskId);
        sb.append(", timeStamp=").append(timeStamp);
        sb.append(", userId=").append(userId);
        sb.append(", lockOwner=").append(lockOwner);
        sb.append(", lockTime=").append(lockTime);
        sb.append(", isProcessed=").append(isProcessed);
        sb.append(", data=").append(data);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}