package com.lind.springboot.generate.model;

import java.io.Serializable;

public class ActGeBytearray implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.NAME_
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.GENERATED_
     *
     * @mbg.generated
     */
    private Byte generated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ge_bytearray.BYTES_
     *
     * @mbg.generated
     */
    private byte[] bytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.ID_
     *
     * @return the value of act_ge_bytearray.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.ID_
     *
     * @param id the value for act_ge_bytearray.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.REV_
     *
     * @return the value of act_ge_bytearray.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.REV_
     *
     * @param rev the value for act_ge_bytearray.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.NAME_
     *
     * @return the value of act_ge_bytearray.NAME_
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.NAME_
     *
     * @param name the value for act_ge_bytearray.NAME_
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @return the value of act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_ge_bytearray.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.GENERATED_
     *
     * @return the value of act_ge_bytearray.GENERATED_
     *
     * @mbg.generated
     */
    public Byte getGenerated() {
        return generated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.GENERATED_
     *
     * @param generated the value for act_ge_bytearray.GENERATED_
     *
     * @mbg.generated
     */
    public void setGenerated(Byte generated) {
        this.generated = generated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ge_bytearray.BYTES_
     *
     * @return the value of act_ge_bytearray.BYTES_
     *
     * @mbg.generated
     */
    public byte[] getBytes() {
        return bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ge_bytearray.BYTES_
     *
     * @param bytes the value for act_ge_bytearray.BYTES_
     *
     * @mbg.generated
     */
    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", name=").append(name);
        sb.append(", deploymentId=").append(deploymentId);
        sb.append(", generated=").append(generated);
        sb.append(", bytes=").append(bytes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}