package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActHiDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TYPE_
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.PROC_INST_ID_
     *
     * @mbg.generated
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.EXECUTION_ID_
     *
     * @mbg.generated
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TASK_ID_
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.ACT_INST_ID_
     *
     * @mbg.generated
     */
    private String actInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.NAME_
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.VAR_TYPE_
     *
     * @mbg.generated
     */
    private String varType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TIME_
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.BYTEARRAY_ID_
     *
     * @mbg.generated
     */
    private String bytearrayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.DOUBLE_
     *
     * @mbg.generated
     */
    private Double double;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.LONG_
     *
     * @mbg.generated
     */
    private Long long;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TEXT_
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TEXT2_
     *
     * @mbg.generated
     */
    private String text2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_hi_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.ID_
     *
     * @return the value of act_hi_detail.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.ID_
     *
     * @param id the value for act_hi_detail.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TYPE_
     *
     * @return the value of act_hi_detail.TYPE_
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TYPE_
     *
     * @param type the value for act_hi_detail.TYPE_
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.PROC_INST_ID_
     *
     * @return the value of act_hi_detail.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_detail.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.EXECUTION_ID_
     *
     * @return the value of act_hi_detail.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.EXECUTION_ID_
     *
     * @param executionId the value for act_hi_detail.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TASK_ID_
     *
     * @return the value of act_hi_detail.TASK_ID_
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TASK_ID_
     *
     * @param taskId the value for act_hi_detail.TASK_ID_
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.ACT_INST_ID_
     *
     * @return the value of act_hi_detail.ACT_INST_ID_
     *
     * @mbg.generated
     */
    public String getActInstId() {
        return actInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.ACT_INST_ID_
     *
     * @param actInstId the value for act_hi_detail.ACT_INST_ID_
     *
     * @mbg.generated
     */
    public void setActInstId(String actInstId) {
        this.actInstId = actInstId == null ? null : actInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.NAME_
     *
     * @return the value of act_hi_detail.NAME_
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.NAME_
     *
     * @param name the value for act_hi_detail.NAME_
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.VAR_TYPE_
     *
     * @return the value of act_hi_detail.VAR_TYPE_
     *
     * @mbg.generated
     */
    public String getVarType() {
        return varType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.VAR_TYPE_
     *
     * @param varType the value for act_hi_detail.VAR_TYPE_
     *
     * @mbg.generated
     */
    public void setVarType(String varType) {
        this.varType = varType == null ? null : varType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.REV_
     *
     * @return the value of act_hi_detail.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.REV_
     *
     * @param rev the value for act_hi_detail.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TIME_
     *
     * @return the value of act_hi_detail.TIME_
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TIME_
     *
     * @param time the value for act_hi_detail.TIME_
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.BYTEARRAY_ID_
     *
     * @return the value of act_hi_detail.BYTEARRAY_ID_
     *
     * @mbg.generated
     */
    public String getBytearrayId() {
        return bytearrayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.BYTEARRAY_ID_
     *
     * @param bytearrayId the value for act_hi_detail.BYTEARRAY_ID_
     *
     * @mbg.generated
     */
    public void setBytearrayId(String bytearrayId) {
        this.bytearrayId = bytearrayId == null ? null : bytearrayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.DOUBLE_
     *
     * @return the value of act_hi_detail.DOUBLE_
     *
     * @mbg.generated
     */
    public Double getDouble() {
        return double;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.DOUBLE_
     *
     * @param double the value for act_hi_detail.DOUBLE_
     *
     * @mbg.generated
     */
    public void setDouble(Double double) {
        this.double = double;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.LONG_
     *
     * @return the value of act_hi_detail.LONG_
     *
     * @mbg.generated
     */
    public Long getLong() {
        return long;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.LONG_
     *
     * @param long the value for act_hi_detail.LONG_
     *
     * @mbg.generated
     */
    public void setLong(Long long) {
        this.long = long;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TEXT_
     *
     * @return the value of act_hi_detail.TEXT_
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TEXT_
     *
     * @param text the value for act_hi_detail.TEXT_
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TEXT2_
     *
     * @return the value of act_hi_detail.TEXT2_
     *
     * @mbg.generated
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TEXT2_
     *
     * @param text2 the value for act_hi_detail.TEXT2_
     *
     * @mbg.generated
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", executionId=").append(executionId);
        sb.append(", taskId=").append(taskId);
        sb.append(", actInstId=").append(actInstId);
        sb.append(", name=").append(name);
        sb.append(", varType=").append(varType);
        sb.append(", rev=").append(rev);
        sb.append(", time=").append(time);
        sb.append(", bytearrayId=").append(bytearrayId);
        sb.append(", double=").append(double);
        sb.append(", long=").append(long);
        sb.append(", text=").append(text);
        sb.append(", text2=").append(text2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}