package com.lind.springboot.generate.model;

import java.io.Serializable;

public class ActHiIdentitylink implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.GROUP_ID_
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.TYPE_
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.USER_ID_
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.TASK_ID_
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_identitylink.PROC_INST_ID_
     *
     * @mbg.generated
     */
    private String procInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.ID_
     *
     * @return the value of act_hi_identitylink.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.ID_
     *
     * @param id the value for act_hi_identitylink.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.GROUP_ID_
     *
     * @return the value of act_hi_identitylink.GROUP_ID_
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.GROUP_ID_
     *
     * @param groupId the value for act_hi_identitylink.GROUP_ID_
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.TYPE_
     *
     * @return the value of act_hi_identitylink.TYPE_
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.TYPE_
     *
     * @param type the value for act_hi_identitylink.TYPE_
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.USER_ID_
     *
     * @return the value of act_hi_identitylink.USER_ID_
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.USER_ID_
     *
     * @param userId the value for act_hi_identitylink.USER_ID_
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.TASK_ID_
     *
     * @return the value of act_hi_identitylink.TASK_ID_
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.TASK_ID_
     *
     * @param taskId the value for act_hi_identitylink.TASK_ID_
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_identitylink.PROC_INST_ID_
     *
     * @return the value of act_hi_identitylink.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_identitylink.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_identitylink.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", type=").append(type);
        sb.append(", userId=").append(userId);
        sb.append(", taskId=").append(taskId);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}