package com.lind.springboot.generate.model;

import java.io.Serializable;

public class ActIdUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_user.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_user.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_user.FIRST_
     *
     * @mbg.generated
     */
    private String first;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_user.LAST_
     *
     * @mbg.generated
     */
    private String last;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_user.EMAIL_
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_user.PWD_
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_user.PICTURE_ID_
     *
     * @mbg.generated
     */
    private String pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_id_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_user.ID_
     *
     * @return the value of act_id_user.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_user.ID_
     *
     * @param id the value for act_id_user.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_user.REV_
     *
     * @return the value of act_id_user.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_user.REV_
     *
     * @param rev the value for act_id_user.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_user.FIRST_
     *
     * @return the value of act_id_user.FIRST_
     *
     * @mbg.generated
     */
    public String getFirst() {
        return first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_user.FIRST_
     *
     * @param first the value for act_id_user.FIRST_
     *
     * @mbg.generated
     */
    public void setFirst(String first) {
        this.first = first == null ? null : first.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_user.LAST_
     *
     * @return the value of act_id_user.LAST_
     *
     * @mbg.generated
     */
    public String getLast() {
        return last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_user.LAST_
     *
     * @param last the value for act_id_user.LAST_
     *
     * @mbg.generated
     */
    public void setLast(String last) {
        this.last = last == null ? null : last.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_user.EMAIL_
     *
     * @return the value of act_id_user.EMAIL_
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_user.EMAIL_
     *
     * @param email the value for act_id_user.EMAIL_
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_user.PWD_
     *
     * @return the value of act_id_user.PWD_
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_user.PWD_
     *
     * @param pwd the value for act_id_user.PWD_
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_user.PICTURE_ID_
     *
     * @return the value of act_id_user.PICTURE_ID_
     *
     * @mbg.generated
     */
    public String getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_user.PICTURE_ID_
     *
     * @param pictureId the value for act_id_user.PICTURE_ID_
     *
     * @mbg.generated
     */
    public void setPictureId(String pictureId) {
        this.pictureId = pictureId == null ? null : pictureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", first=").append(first);
        sb.append(", last=").append(last);
        sb.append(", email=").append(email);
        sb.append(", pwd=").append(pwd);
        sb.append(", pictureId=").append(pictureId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}