package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActRuTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.EXECUTION_ID_
     *
     * @mbg.generated
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.PROC_INST_ID_
     *
     * @mbg.generated
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.NAME_
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.PARENT_TASK_ID_
     *
     * @mbg.generated
     */
    private String parentTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.DESCRIPTION_
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.TASK_DEF_KEY_
     *
     * @mbg.generated
     */
    private String taskDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.OWNER_
     *
     * @mbg.generated
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.ASSIGNEE_
     *
     * @mbg.generated
     */
    private String assignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.DELEGATION_
     *
     * @mbg.generated
     */
    private String delegation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.PRIORITY_
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.CREATE_TIME_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.DUE_DATE_
     *
     * @mbg.generated
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.CATEGORY_
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    private Integer suspensionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.TENANT_ID_
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_task.FORM_KEY_
     *
     * @mbg.generated
     */
    private String formKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_ru_task
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.ID_
     *
     * @return the value of act_ru_task.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.ID_
     *
     * @param id the value for act_ru_task.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.REV_
     *
     * @return the value of act_ru_task.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.REV_
     *
     * @param rev the value for act_ru_task.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.EXECUTION_ID_
     *
     * @return the value of act_ru_task.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.EXECUTION_ID_
     *
     * @param executionId the value for act_ru_task.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.PROC_INST_ID_
     *
     * @return the value of act_ru_task.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.PROC_INST_ID_
     *
     * @param procInstId the value for act_ru_task.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.PROC_DEF_ID_
     *
     * @return the value of act_ru_task.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.PROC_DEF_ID_
     *
     * @param procDefId the value for act_ru_task.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.NAME_
     *
     * @return the value of act_ru_task.NAME_
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.NAME_
     *
     * @param name the value for act_ru_task.NAME_
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.PARENT_TASK_ID_
     *
     * @return the value of act_ru_task.PARENT_TASK_ID_
     *
     * @mbg.generated
     */
    public String getParentTaskId() {
        return parentTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.PARENT_TASK_ID_
     *
     * @param parentTaskId the value for act_ru_task.PARENT_TASK_ID_
     *
     * @mbg.generated
     */
    public void setParentTaskId(String parentTaskId) {
        this.parentTaskId = parentTaskId == null ? null : parentTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.DESCRIPTION_
     *
     * @return the value of act_ru_task.DESCRIPTION_
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.DESCRIPTION_
     *
     * @param description the value for act_ru_task.DESCRIPTION_
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.TASK_DEF_KEY_
     *
     * @return the value of act_ru_task.TASK_DEF_KEY_
     *
     * @mbg.generated
     */
    public String getTaskDefKey() {
        return taskDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.TASK_DEF_KEY_
     *
     * @param taskDefKey the value for act_ru_task.TASK_DEF_KEY_
     *
     * @mbg.generated
     */
    public void setTaskDefKey(String taskDefKey) {
        this.taskDefKey = taskDefKey == null ? null : taskDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.OWNER_
     *
     * @return the value of act_ru_task.OWNER_
     *
     * @mbg.generated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.OWNER_
     *
     * @param owner the value for act_ru_task.OWNER_
     *
     * @mbg.generated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.ASSIGNEE_
     *
     * @return the value of act_ru_task.ASSIGNEE_
     *
     * @mbg.generated
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.ASSIGNEE_
     *
     * @param assignee the value for act_ru_task.ASSIGNEE_
     *
     * @mbg.generated
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee == null ? null : assignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.DELEGATION_
     *
     * @return the value of act_ru_task.DELEGATION_
     *
     * @mbg.generated
     */
    public String getDelegation() {
        return delegation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.DELEGATION_
     *
     * @param delegation the value for act_ru_task.DELEGATION_
     *
     * @mbg.generated
     */
    public void setDelegation(String delegation) {
        this.delegation = delegation == null ? null : delegation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.PRIORITY_
     *
     * @return the value of act_ru_task.PRIORITY_
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.PRIORITY_
     *
     * @param priority the value for act_ru_task.PRIORITY_
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.CREATE_TIME_
     *
     * @return the value of act_ru_task.CREATE_TIME_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.CREATE_TIME_
     *
     * @param createTime the value for act_ru_task.CREATE_TIME_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.DUE_DATE_
     *
     * @return the value of act_ru_task.DUE_DATE_
     *
     * @mbg.generated
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.DUE_DATE_
     *
     * @param dueDate the value for act_ru_task.DUE_DATE_
     *
     * @mbg.generated
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.CATEGORY_
     *
     * @return the value of act_ru_task.CATEGORY_
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.CATEGORY_
     *
     * @param category the value for act_ru_task.CATEGORY_
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.SUSPENSION_STATE_
     *
     * @return the value of act_ru_task.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    public Integer getSuspensionState() {
        return suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.SUSPENSION_STATE_
     *
     * @param suspensionState the value for act_ru_task.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.TENANT_ID_
     *
     * @return the value of act_ru_task.TENANT_ID_
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.TENANT_ID_
     *
     * @param tenantId the value for act_ru_task.TENANT_ID_
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_task.FORM_KEY_
     *
     * @return the value of act_ru_task.FORM_KEY_
     *
     * @mbg.generated
     */
    public String getFormKey() {
        return formKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_task.FORM_KEY_
     *
     * @param formKey the value for act_ru_task.FORM_KEY_
     *
     * @mbg.generated
     */
    public void setFormKey(String formKey) {
        this.formKey = formKey == null ? null : formKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", executionId=").append(executionId);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", procDefId=").append(procDefId);
        sb.append(", name=").append(name);
        sb.append(", parentTaskId=").append(parentTaskId);
        sb.append(", description=").append(description);
        sb.append(", taskDefKey=").append(taskDefKey);
        sb.append(", owner=").append(owner);
        sb.append(", assignee=").append(assignee);
        sb.append(", delegation=").append(delegation);
        sb.append(", priority=").append(priority);
        sb.append(", createTime=").append(createTime);
        sb.append(", dueDate=").append(dueDate);
        sb.append(", category=").append(category);
        sb.append(", suspensionState=").append(suspensionState);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", formKey=").append(formKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}