package com.lind.springboot.generate.model;

import java.io.Serializable;

public class ActReProcdef implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.CATEGORY_
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.NAME_
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.KEY_
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.VERSION_
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.RESOURCE_NAME_
     *
     * @mbg.generated
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated
     */
    private String dgrmResourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.DESCRIPTION_
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbg.generated
     */
    private Byte hasStartFormKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @mbg.generated
     */
    private Byte hasGraphicalNotation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    private Integer suspensionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_procdef.TENANT_ID_
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_re_procdef
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.ID_
     *
     * @return the value of act_re_procdef.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.ID_
     *
     * @param id the value for act_re_procdef.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.REV_
     *
     * @return the value of act_re_procdef.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.REV_
     *
     * @param rev the value for act_re_procdef.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.CATEGORY_
     *
     * @return the value of act_re_procdef.CATEGORY_
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.CATEGORY_
     *
     * @param category the value for act_re_procdef.CATEGORY_
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.NAME_
     *
     * @return the value of act_re_procdef.NAME_
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.NAME_
     *
     * @param name the value for act_re_procdef.NAME_
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.KEY_
     *
     * @return the value of act_re_procdef.KEY_
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.KEY_
     *
     * @param key the value for act_re_procdef.KEY_
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.VERSION_
     *
     * @return the value of act_re_procdef.VERSION_
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.VERSION_
     *
     * @param version the value for act_re_procdef.VERSION_
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @return the value of act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_re_procdef.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.RESOURCE_NAME_
     *
     * @return the value of act_re_procdef.RESOURCE_NAME_
     *
     * @mbg.generated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.RESOURCE_NAME_
     *
     * @param resourceName the value for act_re_procdef.RESOURCE_NAME_
     *
     * @mbg.generated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @return the value of act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated
     */
    public String getDgrmResourceName() {
        return dgrmResourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @param dgrmResourceName the value for act_re_procdef.DGRM_RESOURCE_NAME_
     *
     * @mbg.generated
     */
    public void setDgrmResourceName(String dgrmResourceName) {
        this.dgrmResourceName = dgrmResourceName == null ? null : dgrmResourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.DESCRIPTION_
     *
     * @return the value of act_re_procdef.DESCRIPTION_
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.DESCRIPTION_
     *
     * @param description the value for act_re_procdef.DESCRIPTION_
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @return the value of act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbg.generated
     */
    public Byte getHasStartFormKey() {
        return hasStartFormKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.HAS_START_FORM_KEY_
     *
     * @param hasStartFormKey the value for act_re_procdef.HAS_START_FORM_KEY_
     *
     * @mbg.generated
     */
    public void setHasStartFormKey(Byte hasStartFormKey) {
        this.hasStartFormKey = hasStartFormKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @return the value of act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @mbg.generated
     */
    public Byte getHasGraphicalNotation() {
        return hasGraphicalNotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @param hasGraphicalNotation the value for act_re_procdef.HAS_GRAPHICAL_NOTATION_
     *
     * @mbg.generated
     */
    public void setHasGraphicalNotation(Byte hasGraphicalNotation) {
        this.hasGraphicalNotation = hasGraphicalNotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @return the value of act_re_procdef.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    public Integer getSuspensionState() {
        return suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.SUSPENSION_STATE_
     *
     * @param suspensionState the value for act_re_procdef.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_procdef.TENANT_ID_
     *
     * @return the value of act_re_procdef.TENANT_ID_
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_procdef.TENANT_ID_
     *
     * @param tenantId the value for act_re_procdef.TENANT_ID_
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", category=").append(category);
        sb.append(", name=").append(name);
        sb.append(", key=").append(key);
        sb.append(", version=").append(version);
        sb.append(", deploymentId=").append(deploymentId);
        sb.append(", resourceName=").append(resourceName);
        sb.append(", dgrmResourceName=").append(dgrmResourceName);
        sb.append(", description=").append(description);
        sb.append(", hasStartFormKey=").append(hasStartFormKey);
        sb.append(", hasGraphicalNotation=").append(hasGraphicalNotation);
        sb.append(", suspensionState=").append(suspensionState);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}