package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActRuJob implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.TYPE_
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.LOCK_EXP_TIME_
     *
     * @mbg.generated
     */
    private Date lockExpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.LOCK_OWNER_
     *
     * @mbg.generated
     */
    private String lockOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.EXCLUSIVE_
     *
     * @mbg.generated
     */
    private Boolean exclusive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.EXECUTION_ID_
     *
     * @mbg.generated
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.PROCESS_INSTANCE_ID_
     *
     * @mbg.generated
     */
    private String processInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.RETRIES_
     *
     * @mbg.generated
     */
    private Integer retries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.EXCEPTION_STACK_ID_
     *
     * @mbg.generated
     */
    private String exceptionStackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.EXCEPTION_MSG_
     *
     * @mbg.generated
     */
    private String exceptionMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.DUEDATE_
     *
     * @mbg.generated
     */
    private Date duedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.REPEAT_
     *
     * @mbg.generated
     */
    private String repeat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.HANDLER_TYPE_
     *
     * @mbg.generated
     */
    private String handlerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.HANDLER_CFG_
     *
     * @mbg.generated
     */
    private String handlerCfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_job.TENANT_ID_
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_ru_job
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.ID_
     *
     * @return the value of act_ru_job.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.ID_
     *
     * @param id the value for act_ru_job.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.REV_
     *
     * @return the value of act_ru_job.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.REV_
     *
     * @param rev the value for act_ru_job.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.TYPE_
     *
     * @return the value of act_ru_job.TYPE_
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.TYPE_
     *
     * @param type the value for act_ru_job.TYPE_
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.LOCK_EXP_TIME_
     *
     * @return the value of act_ru_job.LOCK_EXP_TIME_
     *
     * @mbg.generated
     */
    public Date getLockExpTime() {
        return lockExpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.LOCK_EXP_TIME_
     *
     * @param lockExpTime the value for act_ru_job.LOCK_EXP_TIME_
     *
     * @mbg.generated
     */
    public void setLockExpTime(Date lockExpTime) {
        this.lockExpTime = lockExpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.LOCK_OWNER_
     *
     * @return the value of act_ru_job.LOCK_OWNER_
     *
     * @mbg.generated
     */
    public String getLockOwner() {
        return lockOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.LOCK_OWNER_
     *
     * @param lockOwner the value for act_ru_job.LOCK_OWNER_
     *
     * @mbg.generated
     */
    public void setLockOwner(String lockOwner) {
        this.lockOwner = lockOwner == null ? null : lockOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.EXCLUSIVE_
     *
     * @return the value of act_ru_job.EXCLUSIVE_
     *
     * @mbg.generated
     */
    public Boolean getExclusive() {
        return exclusive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.EXCLUSIVE_
     *
     * @param exclusive the value for act_ru_job.EXCLUSIVE_
     *
     * @mbg.generated
     */
    public void setExclusive(Boolean exclusive) {
        this.exclusive = exclusive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.EXECUTION_ID_
     *
     * @return the value of act_ru_job.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.EXECUTION_ID_
     *
     * @param executionId the value for act_ru_job.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.PROCESS_INSTANCE_ID_
     *
     * @return the value of act_ru_job.PROCESS_INSTANCE_ID_
     *
     * @mbg.generated
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.PROCESS_INSTANCE_ID_
     *
     * @param processInstanceId the value for act_ru_job.PROCESS_INSTANCE_ID_
     *
     * @mbg.generated
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId == null ? null : processInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.PROC_DEF_ID_
     *
     * @return the value of act_ru_job.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.PROC_DEF_ID_
     *
     * @param procDefId the value for act_ru_job.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.RETRIES_
     *
     * @return the value of act_ru_job.RETRIES_
     *
     * @mbg.generated
     */
    public Integer getRetries() {
        return retries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.RETRIES_
     *
     * @param retries the value for act_ru_job.RETRIES_
     *
     * @mbg.generated
     */
    public void setRetries(Integer retries) {
        this.retries = retries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.EXCEPTION_STACK_ID_
     *
     * @return the value of act_ru_job.EXCEPTION_STACK_ID_
     *
     * @mbg.generated
     */
    public String getExceptionStackId() {
        return exceptionStackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.EXCEPTION_STACK_ID_
     *
     * @param exceptionStackId the value for act_ru_job.EXCEPTION_STACK_ID_
     *
     * @mbg.generated
     */
    public void setExceptionStackId(String exceptionStackId) {
        this.exceptionStackId = exceptionStackId == null ? null : exceptionStackId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.EXCEPTION_MSG_
     *
     * @return the value of act_ru_job.EXCEPTION_MSG_
     *
     * @mbg.generated
     */
    public String getExceptionMsg() {
        return exceptionMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.EXCEPTION_MSG_
     *
     * @param exceptionMsg the value for act_ru_job.EXCEPTION_MSG_
     *
     * @mbg.generated
     */
    public void setExceptionMsg(String exceptionMsg) {
        this.exceptionMsg = exceptionMsg == null ? null : exceptionMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.DUEDATE_
     *
     * @return the value of act_ru_job.DUEDATE_
     *
     * @mbg.generated
     */
    public Date getDuedate() {
        return duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.DUEDATE_
     *
     * @param duedate the value for act_ru_job.DUEDATE_
     *
     * @mbg.generated
     */
    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.REPEAT_
     *
     * @return the value of act_ru_job.REPEAT_
     *
     * @mbg.generated
     */
    public String getRepeat() {
        return repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.REPEAT_
     *
     * @param repeat the value for act_ru_job.REPEAT_
     *
     * @mbg.generated
     */
    public void setRepeat(String repeat) {
        this.repeat = repeat == null ? null : repeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.HANDLER_TYPE_
     *
     * @return the value of act_ru_job.HANDLER_TYPE_
     *
     * @mbg.generated
     */
    public String getHandlerType() {
        return handlerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.HANDLER_TYPE_
     *
     * @param handlerType the value for act_ru_job.HANDLER_TYPE_
     *
     * @mbg.generated
     */
    public void setHandlerType(String handlerType) {
        this.handlerType = handlerType == null ? null : handlerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.HANDLER_CFG_
     *
     * @return the value of act_ru_job.HANDLER_CFG_
     *
     * @mbg.generated
     */
    public String getHandlerCfg() {
        return handlerCfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.HANDLER_CFG_
     *
     * @param handlerCfg the value for act_ru_job.HANDLER_CFG_
     *
     * @mbg.generated
     */
    public void setHandlerCfg(String handlerCfg) {
        this.handlerCfg = handlerCfg == null ? null : handlerCfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_job.TENANT_ID_
     *
     * @return the value of act_ru_job.TENANT_ID_
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_job.TENANT_ID_
     *
     * @param tenantId the value for act_ru_job.TENANT_ID_
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", type=").append(type);
        sb.append(", lockExpTime=").append(lockExpTime);
        sb.append(", lockOwner=").append(lockOwner);
        sb.append(", exclusive=").append(exclusive);
        sb.append(", executionId=").append(executionId);
        sb.append(", processInstanceId=").append(processInstanceId);
        sb.append(", procDefId=").append(procDefId);
        sb.append(", retries=").append(retries);
        sb.append(", exceptionStackId=").append(exceptionStackId);
        sb.append(", exceptionMsg=").append(exceptionMsg);
        sb.append(", duedate=").append(duedate);
        sb.append(", repeat=").append(repeat);
        sb.append(", handlerType=").append(handlerType);
        sb.append(", handlerCfg=").append(handlerCfg);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}