package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActRuEventSubscr implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.EVENT_TYPE_
     *
     * @mbg.generated
     */
    private String eventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.EVENT_NAME_
     *
     * @mbg.generated
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.EXECUTION_ID_
     *
     * @mbg.generated
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.PROC_INST_ID_
     *
     * @mbg.generated
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.ACTIVITY_ID_
     *
     * @mbg.generated
     */
    private String activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.CONFIGURATION_
     *
     * @mbg.generated
     */
    private String configuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.CREATED_
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_event_subscr.TENANT_ID_
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_ru_event_subscr
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.ID_
     *
     * @return the value of act_ru_event_subscr.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.ID_
     *
     * @param id the value for act_ru_event_subscr.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.REV_
     *
     * @return the value of act_ru_event_subscr.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.REV_
     *
     * @param rev the value for act_ru_event_subscr.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.EVENT_TYPE_
     *
     * @return the value of act_ru_event_subscr.EVENT_TYPE_
     *
     * @mbg.generated
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.EVENT_TYPE_
     *
     * @param eventType the value for act_ru_event_subscr.EVENT_TYPE_
     *
     * @mbg.generated
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.EVENT_NAME_
     *
     * @return the value of act_ru_event_subscr.EVENT_NAME_
     *
     * @mbg.generated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.EVENT_NAME_
     *
     * @param eventName the value for act_ru_event_subscr.EVENT_NAME_
     *
     * @mbg.generated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.EXECUTION_ID_
     *
     * @return the value of act_ru_event_subscr.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.EXECUTION_ID_
     *
     * @param executionId the value for act_ru_event_subscr.EXECUTION_ID_
     *
     * @mbg.generated
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.PROC_INST_ID_
     *
     * @return the value of act_ru_event_subscr.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.PROC_INST_ID_
     *
     * @param procInstId the value for act_ru_event_subscr.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.ACTIVITY_ID_
     *
     * @return the value of act_ru_event_subscr.ACTIVITY_ID_
     *
     * @mbg.generated
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.ACTIVITY_ID_
     *
     * @param activityId the value for act_ru_event_subscr.ACTIVITY_ID_
     *
     * @mbg.generated
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.CONFIGURATION_
     *
     * @return the value of act_ru_event_subscr.CONFIGURATION_
     *
     * @mbg.generated
     */
    public String getConfiguration() {
        return configuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.CONFIGURATION_
     *
     * @param configuration the value for act_ru_event_subscr.CONFIGURATION_
     *
     * @mbg.generated
     */
    public void setConfiguration(String configuration) {
        this.configuration = configuration == null ? null : configuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.CREATED_
     *
     * @return the value of act_ru_event_subscr.CREATED_
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.CREATED_
     *
     * @param created the value for act_ru_event_subscr.CREATED_
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.PROC_DEF_ID_
     *
     * @return the value of act_ru_event_subscr.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.PROC_DEF_ID_
     *
     * @param procDefId the value for act_ru_event_subscr.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_event_subscr.TENANT_ID_
     *
     * @return the value of act_ru_event_subscr.TENANT_ID_
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_event_subscr.TENANT_ID_
     *
     * @param tenantId the value for act_ru_event_subscr.TENANT_ID_
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", eventType=").append(eventType);
        sb.append(", eventName=").append(eventName);
        sb.append(", executionId=").append(executionId);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", activityId=").append(activityId);
        sb.append(", configuration=").append(configuration);
        sb.append(", created=").append(created);
        sb.append(", procDefId=").append(procDefId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}