package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActRuExecution implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.PROC_INST_ID_
     *
     * @mbg.generated
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.BUSINESS_KEY_
     *
     * @mbg.generated
     */
    private String businessKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.PARENT_ID_
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.SUPER_EXEC_
     *
     * @mbg.generated
     */
    private String superExec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.ACT_ID_
     *
     * @mbg.generated
     */
    private String actId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.IS_ACTIVE_
     *
     * @mbg.generated
     */
    private Byte isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.IS_CONCURRENT_
     *
     * @mbg.generated
     */
    private Byte isConcurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.IS_SCOPE_
     *
     * @mbg.generated
     */
    private Byte isScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.IS_EVENT_SCOPE_
     *
     * @mbg.generated
     */
    private Byte isEventScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    private Integer suspensionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.CACHED_ENT_STATE_
     *
     * @mbg.generated
     */
    private Integer cachedEntState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.TENANT_ID_
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.NAME_
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_ru_execution.LOCK_TIME_
     *
     * @mbg.generated
     */
    private Date lockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_ru_execution
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.ID_
     *
     * @return the value of act_ru_execution.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.ID_
     *
     * @param id the value for act_ru_execution.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.REV_
     *
     * @return the value of act_ru_execution.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.REV_
     *
     * @param rev the value for act_ru_execution.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.PROC_INST_ID_
     *
     * @return the value of act_ru_execution.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.PROC_INST_ID_
     *
     * @param procInstId the value for act_ru_execution.PROC_INST_ID_
     *
     * @mbg.generated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.BUSINESS_KEY_
     *
     * @return the value of act_ru_execution.BUSINESS_KEY_
     *
     * @mbg.generated
     */
    public String getBusinessKey() {
        return businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.BUSINESS_KEY_
     *
     * @param businessKey the value for act_ru_execution.BUSINESS_KEY_
     *
     * @mbg.generated
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey == null ? null : businessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.PARENT_ID_
     *
     * @return the value of act_ru_execution.PARENT_ID_
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.PARENT_ID_
     *
     * @param parentId the value for act_ru_execution.PARENT_ID_
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.PROC_DEF_ID_
     *
     * @return the value of act_ru_execution.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.PROC_DEF_ID_
     *
     * @param procDefId the value for act_ru_execution.PROC_DEF_ID_
     *
     * @mbg.generated
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.SUPER_EXEC_
     *
     * @return the value of act_ru_execution.SUPER_EXEC_
     *
     * @mbg.generated
     */
    public String getSuperExec() {
        return superExec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.SUPER_EXEC_
     *
     * @param superExec the value for act_ru_execution.SUPER_EXEC_
     *
     * @mbg.generated
     */
    public void setSuperExec(String superExec) {
        this.superExec = superExec == null ? null : superExec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.ACT_ID_
     *
     * @return the value of act_ru_execution.ACT_ID_
     *
     * @mbg.generated
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.ACT_ID_
     *
     * @param actId the value for act_ru_execution.ACT_ID_
     *
     * @mbg.generated
     */
    public void setActId(String actId) {
        this.actId = actId == null ? null : actId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.IS_ACTIVE_
     *
     * @return the value of act_ru_execution.IS_ACTIVE_
     *
     * @mbg.generated
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.IS_ACTIVE_
     *
     * @param isActive the value for act_ru_execution.IS_ACTIVE_
     *
     * @mbg.generated
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.IS_CONCURRENT_
     *
     * @return the value of act_ru_execution.IS_CONCURRENT_
     *
     * @mbg.generated
     */
    public Byte getIsConcurrent() {
        return isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.IS_CONCURRENT_
     *
     * @param isConcurrent the value for act_ru_execution.IS_CONCURRENT_
     *
     * @mbg.generated
     */
    public void setIsConcurrent(Byte isConcurrent) {
        this.isConcurrent = isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.IS_SCOPE_
     *
     * @return the value of act_ru_execution.IS_SCOPE_
     *
     * @mbg.generated
     */
    public Byte getIsScope() {
        return isScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.IS_SCOPE_
     *
     * @param isScope the value for act_ru_execution.IS_SCOPE_
     *
     * @mbg.generated
     */
    public void setIsScope(Byte isScope) {
        this.isScope = isScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.IS_EVENT_SCOPE_
     *
     * @return the value of act_ru_execution.IS_EVENT_SCOPE_
     *
     * @mbg.generated
     */
    public Byte getIsEventScope() {
        return isEventScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.IS_EVENT_SCOPE_
     *
     * @param isEventScope the value for act_ru_execution.IS_EVENT_SCOPE_
     *
     * @mbg.generated
     */
    public void setIsEventScope(Byte isEventScope) {
        this.isEventScope = isEventScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.SUSPENSION_STATE_
     *
     * @return the value of act_ru_execution.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    public Integer getSuspensionState() {
        return suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.SUSPENSION_STATE_
     *
     * @param suspensionState the value for act_ru_execution.SUSPENSION_STATE_
     *
     * @mbg.generated
     */
    public void setSuspensionState(Integer suspensionState) {
        this.suspensionState = suspensionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.CACHED_ENT_STATE_
     *
     * @return the value of act_ru_execution.CACHED_ENT_STATE_
     *
     * @mbg.generated
     */
    public Integer getCachedEntState() {
        return cachedEntState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.CACHED_ENT_STATE_
     *
     * @param cachedEntState the value for act_ru_execution.CACHED_ENT_STATE_
     *
     * @mbg.generated
     */
    public void setCachedEntState(Integer cachedEntState) {
        this.cachedEntState = cachedEntState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.TENANT_ID_
     *
     * @return the value of act_ru_execution.TENANT_ID_
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.TENANT_ID_
     *
     * @param tenantId the value for act_ru_execution.TENANT_ID_
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.NAME_
     *
     * @return the value of act_ru_execution.NAME_
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.NAME_
     *
     * @param name the value for act_ru_execution.NAME_
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_ru_execution.LOCK_TIME_
     *
     * @return the value of act_ru_execution.LOCK_TIME_
     *
     * @mbg.generated
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_ru_execution.LOCK_TIME_
     *
     * @param lockTime the value for act_ru_execution.LOCK_TIME_
     *
     * @mbg.generated
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_execution
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", businessKey=").append(businessKey);
        sb.append(", parentId=").append(parentId);
        sb.append(", procDefId=").append(procDefId);
        sb.append(", superExec=").append(superExec);
        sb.append(", actId=").append(actId);
        sb.append(", isActive=").append(isActive);
        sb.append(", isConcurrent=").append(isConcurrent);
        sb.append(", isScope=").append(isScope);
        sb.append(", isEventScope=").append(isEventScope);
        sb.append(", suspensionState=").append(suspensionState);
        sb.append(", cachedEntState=").append(cachedEntState);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", name=").append(name);
        sb.append(", lockTime=").append(lockTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}