package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActReModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.REV_
     *
     * @mbg.generated
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.NAME_
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.KEY_
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.CATEGORY_
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.CREATE_TIME_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.LAST_UPDATE_TIME_
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.VERSION_
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.META_INFO_
     *
     * @mbg.generated
     */
    private String metaInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @mbg.generated
     */
    private String editorSourceValueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @mbg.generated
     */
    private String editorSourceExtraValueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_model.TENANT_ID_
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_re_model
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.ID_
     *
     * @return the value of act_re_model.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.ID_
     *
     * @param id the value for act_re_model.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.REV_
     *
     * @return the value of act_re_model.REV_
     *
     * @mbg.generated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.REV_
     *
     * @param rev the value for act_re_model.REV_
     *
     * @mbg.generated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.NAME_
     *
     * @return the value of act_re_model.NAME_
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.NAME_
     *
     * @param name the value for act_re_model.NAME_
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.KEY_
     *
     * @return the value of act_re_model.KEY_
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.KEY_
     *
     * @param key the value for act_re_model.KEY_
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.CATEGORY_
     *
     * @return the value of act_re_model.CATEGORY_
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.CATEGORY_
     *
     * @param category the value for act_re_model.CATEGORY_
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.CREATE_TIME_
     *
     * @return the value of act_re_model.CREATE_TIME_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.CREATE_TIME_
     *
     * @param createTime the value for act_re_model.CREATE_TIME_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.LAST_UPDATE_TIME_
     *
     * @return the value of act_re_model.LAST_UPDATE_TIME_
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.LAST_UPDATE_TIME_
     *
     * @param lastUpdateTime the value for act_re_model.LAST_UPDATE_TIME_
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.VERSION_
     *
     * @return the value of act_re_model.VERSION_
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.VERSION_
     *
     * @param version the value for act_re_model.VERSION_
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.META_INFO_
     *
     * @return the value of act_re_model.META_INFO_
     *
     * @mbg.generated
     */
    public String getMetaInfo() {
        return metaInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.META_INFO_
     *
     * @param metaInfo the value for act_re_model.META_INFO_
     *
     * @mbg.generated
     */
    public void setMetaInfo(String metaInfo) {
        this.metaInfo = metaInfo == null ? null : metaInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.DEPLOYMENT_ID_
     *
     * @return the value of act_re_model.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.DEPLOYMENT_ID_
     *
     * @param deploymentId the value for act_re_model.DEPLOYMENT_ID_
     *
     * @mbg.generated
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @return the value of act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @mbg.generated
     */
    public String getEditorSourceValueId() {
        return editorSourceValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @param editorSourceValueId the value for act_re_model.EDITOR_SOURCE_VALUE_ID_
     *
     * @mbg.generated
     */
    public void setEditorSourceValueId(String editorSourceValueId) {
        this.editorSourceValueId = editorSourceValueId == null ? null : editorSourceValueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @return the value of act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @mbg.generated
     */
    public String getEditorSourceExtraValueId() {
        return editorSourceExtraValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @param editorSourceExtraValueId the value for act_re_model.EDITOR_SOURCE_EXTRA_VALUE_ID_
     *
     * @mbg.generated
     */
    public void setEditorSourceExtraValueId(String editorSourceExtraValueId) {
        this.editorSourceExtraValueId = editorSourceExtraValueId == null ? null : editorSourceExtraValueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_model.TENANT_ID_
     *
     * @return the value of act_re_model.TENANT_ID_
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_model.TENANT_ID_
     *
     * @param tenantId the value for act_re_model.TENANT_ID_
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rev=").append(rev);
        sb.append(", name=").append(name);
        sb.append(", key=").append(key);
        sb.append(", category=").append(category);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", version=").append(version);
        sb.append(", metaInfo=").append(metaInfo);
        sb.append(", deploymentId=").append(deploymentId);
        sb.append(", editorSourceValueId=").append(editorSourceValueId);
        sb.append(", editorSourceExtraValueId=").append(editorSourceExtraValueId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}