package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class ActReDeployment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.ID_
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.NAME_
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.CATEGORY_
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.TENANT_ID_
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_re_deployment.DEPLOY_TIME_
     *
     * @mbg.generated
     */
    private Date deployTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table act_re_deployment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.ID_
     *
     * @return the value of act_re_deployment.ID_
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.ID_
     *
     * @param id the value for act_re_deployment.ID_
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.NAME_
     *
     * @return the value of act_re_deployment.NAME_
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.NAME_
     *
     * @param name the value for act_re_deployment.NAME_
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.CATEGORY_
     *
     * @return the value of act_re_deployment.CATEGORY_
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.CATEGORY_
     *
     * @param category the value for act_re_deployment.CATEGORY_
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.TENANT_ID_
     *
     * @return the value of act_re_deployment.TENANT_ID_
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.TENANT_ID_
     *
     * @param tenantId the value for act_re_deployment.TENANT_ID_
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_re_deployment.DEPLOY_TIME_
     *
     * @return the value of act_re_deployment.DEPLOY_TIME_
     *
     * @mbg.generated
     */
    public Date getDeployTime() {
        return deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_re_deployment.DEPLOY_TIME_
     *
     * @param deployTime the value for act_re_deployment.DEPLOY_TIME_
     *
     * @mbg.generated
     */
    public void setDeployTime(Date deployTime) {
        this.deployTime = deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", category=").append(category);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", deployTime=").append(deployTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}