package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class TActProcess implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.category_id
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.deployment_id
     *
     * @mbg.generated
     */
    private String deploymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.diagram_name
     *
     * @mbg.generated
     */
    private String diagramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.latest
     *
     * @mbg.generated
     */
    private Boolean latest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.process_key
     *
     * @mbg.generated
     */
    private String processKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.xml_name
     *
     * @mbg.generated
     */
    private String xmlName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.business_table
     *
     * @mbg.generated
     */
    private String businessTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.route_name
     *
     * @mbg.generated
     */
    private String routeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.create_department_id
     *
     * @mbg.generated
     */
    private String createDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.create_department_ids
     *
     * @mbg.generated
     */
    private String createDepartmentIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.update_department_id
     *
     * @mbg.generated
     */
    private String updateDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_process.update_department_ids
     *
     * @mbg.generated
     */
    private String updateDepartmentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_act_process
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.id
     *
     * @return the value of t_act_process.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.id
     *
     * @param id the value for t_act_process.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.create_by
     *
     * @return the value of t_act_process.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.create_by
     *
     * @param createBy the value for t_act_process.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.create_time
     *
     * @return the value of t_act_process.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.create_time
     *
     * @param createTime the value for t_act_process.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.del_flag
     *
     * @return the value of t_act_process.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.del_flag
     *
     * @param delFlag the value for t_act_process.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.update_by
     *
     * @return the value of t_act_process.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.update_by
     *
     * @param updateBy the value for t_act_process.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.update_time
     *
     * @return the value of t_act_process.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.update_time
     *
     * @param updateTime the value for t_act_process.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.category_id
     *
     * @return the value of t_act_process.category_id
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.category_id
     *
     * @param categoryId the value for t_act_process.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.deployment_id
     *
     * @return the value of t_act_process.deployment_id
     *
     * @mbg.generated
     */
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.deployment_id
     *
     * @param deploymentId the value for t_act_process.deployment_id
     *
     * @mbg.generated
     */
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId == null ? null : deploymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.description
     *
     * @return the value of t_act_process.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.description
     *
     * @param description the value for t_act_process.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.diagram_name
     *
     * @return the value of t_act_process.diagram_name
     *
     * @mbg.generated
     */
    public String getDiagramName() {
        return diagramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.diagram_name
     *
     * @param diagramName the value for t_act_process.diagram_name
     *
     * @mbg.generated
     */
    public void setDiagramName(String diagramName) {
        this.diagramName = diagramName == null ? null : diagramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.latest
     *
     * @return the value of t_act_process.latest
     *
     * @mbg.generated
     */
    public Boolean getLatest() {
        return latest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.latest
     *
     * @param latest the value for t_act_process.latest
     *
     * @mbg.generated
     */
    public void setLatest(Boolean latest) {
        this.latest = latest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.name
     *
     * @return the value of t_act_process.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.name
     *
     * @param name the value for t_act_process.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.process_key
     *
     * @return the value of t_act_process.process_key
     *
     * @mbg.generated
     */
    public String getProcessKey() {
        return processKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.process_key
     *
     * @param processKey the value for t_act_process.process_key
     *
     * @mbg.generated
     */
    public void setProcessKey(String processKey) {
        this.processKey = processKey == null ? null : processKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.status
     *
     * @return the value of t_act_process.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.status
     *
     * @param status the value for t_act_process.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.version
     *
     * @return the value of t_act_process.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.version
     *
     * @param version the value for t_act_process.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.xml_name
     *
     * @return the value of t_act_process.xml_name
     *
     * @mbg.generated
     */
    public String getXmlName() {
        return xmlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.xml_name
     *
     * @param xmlName the value for t_act_process.xml_name
     *
     * @mbg.generated
     */
    public void setXmlName(String xmlName) {
        this.xmlName = xmlName == null ? null : xmlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.business_table
     *
     * @return the value of t_act_process.business_table
     *
     * @mbg.generated
     */
    public String getBusinessTable() {
        return businessTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.business_table
     *
     * @param businessTable the value for t_act_process.business_table
     *
     * @mbg.generated
     */
    public void setBusinessTable(String businessTable) {
        this.businessTable = businessTable == null ? null : businessTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.route_name
     *
     * @return the value of t_act_process.route_name
     *
     * @mbg.generated
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.route_name
     *
     * @param routeName the value for t_act_process.route_name
     *
     * @mbg.generated
     */
    public void setRouteName(String routeName) {
        this.routeName = routeName == null ? null : routeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.create_department_id
     *
     * @return the value of t_act_process.create_department_id
     *
     * @mbg.generated
     */
    public String getCreateDepartmentId() {
        return createDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.create_department_id
     *
     * @param createDepartmentId the value for t_act_process.create_department_id
     *
     * @mbg.generated
     */
    public void setCreateDepartmentId(String createDepartmentId) {
        this.createDepartmentId = createDepartmentId == null ? null : createDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.tenant_id
     *
     * @return the value of t_act_process.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.tenant_id
     *
     * @param tenantId the value for t_act_process.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.create_department_ids
     *
     * @return the value of t_act_process.create_department_ids
     *
     * @mbg.generated
     */
    public String getCreateDepartmentIds() {
        return createDepartmentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.create_department_ids
     *
     * @param createDepartmentIds the value for t_act_process.create_department_ids
     *
     * @mbg.generated
     */
    public void setCreateDepartmentIds(String createDepartmentIds) {
        this.createDepartmentIds = createDepartmentIds == null ? null : createDepartmentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.update_department_id
     *
     * @return the value of t_act_process.update_department_id
     *
     * @mbg.generated
     */
    public String getUpdateDepartmentId() {
        return updateDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.update_department_id
     *
     * @param updateDepartmentId the value for t_act_process.update_department_id
     *
     * @mbg.generated
     */
    public void setUpdateDepartmentId(String updateDepartmentId) {
        this.updateDepartmentId = updateDepartmentId == null ? null : updateDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_process.update_department_ids
     *
     * @return the value of t_act_process.update_department_ids
     *
     * @mbg.generated
     */
    public String getUpdateDepartmentIds() {
        return updateDepartmentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_process.update_department_ids
     *
     * @param updateDepartmentIds the value for t_act_process.update_department_ids
     *
     * @mbg.generated
     */
    public void setUpdateDepartmentIds(String updateDepartmentIds) {
        this.updateDepartmentIds = updateDepartmentIds == null ? null : updateDepartmentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_process
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", deploymentId=").append(deploymentId);
        sb.append(", description=").append(description);
        sb.append(", diagramName=").append(diagramName);
        sb.append(", latest=").append(latest);
        sb.append(", name=").append(name);
        sb.append(", processKey=").append(processKey);
        sb.append(", status=").append(status);
        sb.append(", version=").append(version);
        sb.append(", xmlName=").append(xmlName);
        sb.append(", businessTable=").append(businessTable);
        sb.append(", routeName=").append(routeName);
        sb.append(", createDepartmentId=").append(createDepartmentId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", createDepartmentIds=").append(createDepartmentIds);
        sb.append(", updateDepartmentId=").append(updateDepartmentId);
        sb.append(", updateDepartmentIds=").append(updateDepartmentIds);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}