package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class TActBusiness implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.table_id
     *
     * @mbg.generated
     */
    private String tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.business_type
     *
     * @mbg.generated
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.proc_def_id
     *
     * @mbg.generated
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.proc_inst_id
     *
     * @mbg.generated
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.apply_time
     *
     * @mbg.generated
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.create_department_id
     *
     * @mbg.generated
     */
    private String createDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.create_department_ids
     *
     * @mbg.generated
     */
    private String createDepartmentIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.update_department_id
     *
     * @mbg.generated
     */
    private String updateDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.update_department_ids
     *
     * @mbg.generated
     */
    private String updateDepartmentIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.back_flow
     *
     * @mbg.generated
     */
    private String backFlow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_business.retreat_id
     *
     * @mbg.generated
     */
    private String retreatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_act_business
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.id
     *
     * @return the value of t_act_business.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.id
     *
     * @param id the value for t_act_business.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.result
     *
     * @return the value of t_act_business.result
     *
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.result
     *
     * @param result the value for t_act_business.result
     *
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.title
     *
     * @return the value of t_act_business.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.title
     *
     * @param title the value for t_act_business.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.status
     *
     * @return the value of t_act_business.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.status
     *
     * @param status the value for t_act_business.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.table_id
     *
     * @return the value of t_act_business.table_id
     *
     * @mbg.generated
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.table_id
     *
     * @param tableId the value for t_act_business.table_id
     *
     * @mbg.generated
     */
    public void setTableId(String tableId) {
        this.tableId = tableId == null ? null : tableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.business_type
     *
     * @return the value of t_act_business.business_type
     *
     * @mbg.generated
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.business_type
     *
     * @param businessType the value for t_act_business.business_type
     *
     * @mbg.generated
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.proc_def_id
     *
     * @return the value of t_act_business.proc_def_id
     *
     * @mbg.generated
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.proc_def_id
     *
     * @param procDefId the value for t_act_business.proc_def_id
     *
     * @mbg.generated
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.proc_inst_id
     *
     * @return the value of t_act_business.proc_inst_id
     *
     * @mbg.generated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.proc_inst_id
     *
     * @param procInstId the value for t_act_business.proc_inst_id
     *
     * @mbg.generated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.user_id
     *
     * @return the value of t_act_business.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.user_id
     *
     * @param userId the value for t_act_business.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.create_by
     *
     * @return the value of t_act_business.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.create_by
     *
     * @param createBy the value for t_act_business.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.create_time
     *
     * @return the value of t_act_business.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.create_time
     *
     * @param createTime the value for t_act_business.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.del_flag
     *
     * @return the value of t_act_business.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.del_flag
     *
     * @param delFlag the value for t_act_business.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.update_by
     *
     * @return the value of t_act_business.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.update_by
     *
     * @param updateBy the value for t_act_business.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.update_time
     *
     * @return the value of t_act_business.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.update_time
     *
     * @param updateTime the value for t_act_business.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.apply_time
     *
     * @return the value of t_act_business.apply_time
     *
     * @mbg.generated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.apply_time
     *
     * @param applyTime the value for t_act_business.apply_time
     *
     * @mbg.generated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.create_department_id
     *
     * @return the value of t_act_business.create_department_id
     *
     * @mbg.generated
     */
    public String getCreateDepartmentId() {
        return createDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.create_department_id
     *
     * @param createDepartmentId the value for t_act_business.create_department_id
     *
     * @mbg.generated
     */
    public void setCreateDepartmentId(String createDepartmentId) {
        this.createDepartmentId = createDepartmentId == null ? null : createDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.tenant_id
     *
     * @return the value of t_act_business.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.tenant_id
     *
     * @param tenantId the value for t_act_business.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.create_department_ids
     *
     * @return the value of t_act_business.create_department_ids
     *
     * @mbg.generated
     */
    public String getCreateDepartmentIds() {
        return createDepartmentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.create_department_ids
     *
     * @param createDepartmentIds the value for t_act_business.create_department_ids
     *
     * @mbg.generated
     */
    public void setCreateDepartmentIds(String createDepartmentIds) {
        this.createDepartmentIds = createDepartmentIds == null ? null : createDepartmentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.update_department_id
     *
     * @return the value of t_act_business.update_department_id
     *
     * @mbg.generated
     */
    public String getUpdateDepartmentId() {
        return updateDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.update_department_id
     *
     * @param updateDepartmentId the value for t_act_business.update_department_id
     *
     * @mbg.generated
     */
    public void setUpdateDepartmentId(String updateDepartmentId) {
        this.updateDepartmentId = updateDepartmentId == null ? null : updateDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.update_department_ids
     *
     * @return the value of t_act_business.update_department_ids
     *
     * @mbg.generated
     */
    public String getUpdateDepartmentIds() {
        return updateDepartmentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.update_department_ids
     *
     * @param updateDepartmentIds the value for t_act_business.update_department_ids
     *
     * @mbg.generated
     */
    public void setUpdateDepartmentIds(String updateDepartmentIds) {
        this.updateDepartmentIds = updateDepartmentIds == null ? null : updateDepartmentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.back_flow
     *
     * @return the value of t_act_business.back_flow
     *
     * @mbg.generated
     */
    public String getBackFlow() {
        return backFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.back_flow
     *
     * @param backFlow the value for t_act_business.back_flow
     *
     * @mbg.generated
     */
    public void setBackFlow(String backFlow) {
        this.backFlow = backFlow == null ? null : backFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_business.retreat_id
     *
     * @return the value of t_act_business.retreat_id
     *
     * @mbg.generated
     */
    public String getRetreatId() {
        return retreatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_business.retreat_id
     *
     * @param retreatId the value for t_act_business.retreat_id
     *
     * @mbg.generated
     */
    public void setRetreatId(String retreatId) {
        this.retreatId = retreatId == null ? null : retreatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_business
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", result=").append(result);
        sb.append(", title=").append(title);
        sb.append(", status=").append(status);
        sb.append(", tableId=").append(tableId);
        sb.append(", businessType=").append(businessType);
        sb.append(", procDefId=").append(procDefId);
        sb.append(", procInstId=").append(procInstId);
        sb.append(", userId=").append(userId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", applyTime=").append(applyTime);
        sb.append(", createDepartmentId=").append(createDepartmentId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", createDepartmentIds=").append(createDepartmentIds);
        sb.append(", updateDepartmentId=").append(updateDepartmentId);
        sb.append(", updateDepartmentIds=").append(updateDepartmentIds);
        sb.append(", backFlow=").append(backFlow);
        sb.append(", retreatId=").append(retreatId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}