package com.lind.springboot.generate.model;

import java.io.Serializable;
import java.util.Date;

public class TActNode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.node_id
     *
     * @mbg.generated
     */
    private String nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.relate_id
     *
     * @mbg.generated
     */
    private String relateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.create_department_id
     *
     * @mbg.generated
     */
    private String createDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.create_department_ids
     *
     * @mbg.generated
     */
    private String createDepartmentIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.update_department_id
     *
     * @mbg.generated
     */
    private String updateDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_act_node.update_department_ids
     *
     * @mbg.generated
     */
    private String updateDepartmentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_act_node
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.id
     *
     * @return the value of t_act_node.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.id
     *
     * @param id the value for t_act_node.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.create_by
     *
     * @return the value of t_act_node.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.create_by
     *
     * @param createBy the value for t_act_node.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.create_time
     *
     * @return the value of t_act_node.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.create_time
     *
     * @param createTime the value for t_act_node.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.del_flag
     *
     * @return the value of t_act_node.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.del_flag
     *
     * @param delFlag the value for t_act_node.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.update_by
     *
     * @return the value of t_act_node.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.update_by
     *
     * @param updateBy the value for t_act_node.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.update_time
     *
     * @return the value of t_act_node.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.update_time
     *
     * @param updateTime the value for t_act_node.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.node_id
     *
     * @return the value of t_act_node.node_id
     *
     * @mbg.generated
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.node_id
     *
     * @param nodeId the value for t_act_node.node_id
     *
     * @mbg.generated
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.role_id
     *
     * @return the value of t_act_node.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.role_id
     *
     * @param roleId the value for t_act_node.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.type
     *
     * @return the value of t_act_node.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.type
     *
     * @param type the value for t_act_node.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.user_id
     *
     * @return the value of t_act_node.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.user_id
     *
     * @param userId the value for t_act_node.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.relate_id
     *
     * @return the value of t_act_node.relate_id
     *
     * @mbg.generated
     */
    public String getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.relate_id
     *
     * @param relateId the value for t_act_node.relate_id
     *
     * @mbg.generated
     */
    public void setRelateId(String relateId) {
        this.relateId = relateId == null ? null : relateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.create_department_id
     *
     * @return the value of t_act_node.create_department_id
     *
     * @mbg.generated
     */
    public String getCreateDepartmentId() {
        return createDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.create_department_id
     *
     * @param createDepartmentId the value for t_act_node.create_department_id
     *
     * @mbg.generated
     */
    public void setCreateDepartmentId(String createDepartmentId) {
        this.createDepartmentId = createDepartmentId == null ? null : createDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.tenant_id
     *
     * @return the value of t_act_node.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.tenant_id
     *
     * @param tenantId the value for t_act_node.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.create_department_ids
     *
     * @return the value of t_act_node.create_department_ids
     *
     * @mbg.generated
     */
    public String getCreateDepartmentIds() {
        return createDepartmentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.create_department_ids
     *
     * @param createDepartmentIds the value for t_act_node.create_department_ids
     *
     * @mbg.generated
     */
    public void setCreateDepartmentIds(String createDepartmentIds) {
        this.createDepartmentIds = createDepartmentIds == null ? null : createDepartmentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.update_department_id
     *
     * @return the value of t_act_node.update_department_id
     *
     * @mbg.generated
     */
    public String getUpdateDepartmentId() {
        return updateDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.update_department_id
     *
     * @param updateDepartmentId the value for t_act_node.update_department_id
     *
     * @mbg.generated
     */
    public void setUpdateDepartmentId(String updateDepartmentId) {
        this.updateDepartmentId = updateDepartmentId == null ? null : updateDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_act_node.update_department_ids
     *
     * @return the value of t_act_node.update_department_ids
     *
     * @mbg.generated
     */
    public String getUpdateDepartmentIds() {
        return updateDepartmentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_act_node.update_department_ids
     *
     * @param updateDepartmentIds the value for t_act_node.update_department_ids
     *
     * @mbg.generated
     */
    public void setUpdateDepartmentIds(String updateDepartmentIds) {
        this.updateDepartmentIds = updateDepartmentIds == null ? null : updateDepartmentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_node
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", nodeId=").append(nodeId);
        sb.append(", roleId=").append(roleId);
        sb.append(", type=").append(type);
        sb.append(", userId=").append(userId);
        sb.append(", relateId=").append(relateId);
        sb.append(", createDepartmentId=").append(createDepartmentId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", createDepartmentIds=").append(createDepartmentIds);
        sb.append(", updateDepartmentId=").append(updateDepartmentId);
        sb.append(", updateDepartmentIds=").append(updateDepartmentIds);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}