package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActEvtLog;
import java.util.List;

public interface ActEvtLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long logNr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbg.generated
     */
    int insert(ActEvtLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbg.generated
     */
    ActEvtLog selectByPrimaryKey(Long logNr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbg.generated
     */
    List<ActEvtLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_evt_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActEvtLog record);
}