package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActGeBytearray;
import java.util.List;

public interface ActGeBytearrayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated
     */
    int insert(ActGeBytearray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated
     */
    ActGeBytearray selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated
     */
    List<ActGeBytearray> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_bytearray
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActGeBytearray record);
}