package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActGeProperty;
import java.util.List;

public interface ActGePropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated
     */
    int insert(ActGeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated
     */
    ActGeProperty selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated
     */
    List<ActGeProperty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActGeProperty record);
}