package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActHiComment;
import java.util.List;

public interface ActHiCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated
     */
    int insert(ActHiComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated
     */
    ActHiComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated
     */
    List<ActHiComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActHiComment record);
}