package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActHiVarinst;
import java.util.List;

public interface ActHiVarinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated
     */
    int insert(ActHiVarinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated
     */
    ActHiVarinst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated
     */
    List<ActHiVarinst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActHiVarinst record);
}