package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActHiProcinst;
import java.util.List;

public interface ActHiProcinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbg.generated
     */
    int insert(ActHiProcinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbg.generated
     */
    ActHiProcinst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbg.generated
     */
    List<ActHiProcinst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_procinst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActHiProcinst record);
}