package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActHiIdentitylink;
import java.util.List;

public interface ActHiIdentitylinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated
     */
    int insert(ActHiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated
     */
    ActHiIdentitylink selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated
     */
    List<ActHiIdentitylink> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActHiIdentitylink record);
}