package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActHiActinst;
import java.util.List;

public interface ActHiActinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated
     */
    int insert(ActHiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated
     */
    ActHiActinst selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated
     */
    List<ActHiActinst> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActHiActinst record);
}