package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActIdInfo;
import java.util.List;

public interface ActIdInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_info
     *
     * @mbg.generated
     */
    int insert(ActIdInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_info
     *
     * @mbg.generated
     */
    ActIdInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_info
     *
     * @mbg.generated
     */
    List<ActIdInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActIdInfo record);
}