package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActIdMembership;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActIdMembershipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("groupId") String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbg.generated
     */
    int insert(ActIdMembership record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbg.generated
     */
    List<ActIdMembership> selectAll();
}