package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActReProcdef;
import java.util.List;

public interface ActReProcdefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated
     */
    int insert(ActReProcdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated
     */
    ActReProcdef selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated
     */
    List<ActReProcdef> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActReProcdef record);
}