package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActRuTask;
import java.util.List;

public interface ActRuTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbg.generated
     */
    int insert(ActRuTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbg.generated
     */
    ActRuTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbg.generated
     */
    List<ActRuTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActRuTask record);
}