package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActRuEventSubscr;
import java.util.List;

public interface ActRuEventSubscrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbg.generated
     */
    int insert(ActRuEventSubscr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbg.generated
     */
    ActRuEventSubscr selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbg.generated
     */
    List<ActRuEventSubscr> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_event_subscr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActRuEventSubscr record);
}