package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActReDeployment;
import java.util.List;

public interface ActReDeploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbg.generated
     */
    int insert(ActReDeployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbg.generated
     */
    ActReDeployment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbg.generated
     */
    List<ActReDeployment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_deployment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActReDeployment record);
}