package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActRuJob;
import java.util.List;

public interface ActRuJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated
     */
    int insert(ActRuJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated
     */
    ActRuJob selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated
     */
    List<ActRuJob> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActRuJob record);
}