package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.ActRuVariable;
import java.util.List;

public interface ActRuVariableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated
     */
    int insert(ActRuVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated
     */
    ActRuVariable selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated
     */
    List<ActRuVariable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActRuVariable record);
}