package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.TActProcess;
import java.util.List;

public interface TActProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_process
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_process
     *
     * @mbg.generated
     */
    int insert(TActProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_process
     *
     * @mbg.generated
     */
    TActProcess selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_process
     *
     * @mbg.generated
     */
    List<TActProcess> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TActProcess record);
}