package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.TActBusiness;
import java.util.List;

public interface TActBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_business
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_business
     *
     * @mbg.generated
     */
    int insert(TActBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_business
     *
     * @mbg.generated
     */
    TActBusiness selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_business
     *
     * @mbg.generated
     */
    List<TActBusiness> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_business
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TActBusiness record);
}