package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.TActCategory;
import java.util.List;

public interface TActCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_category
     *
     * @mbg.generated
     */
    int insert(TActCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_category
     *
     * @mbg.generated
     */
    TActCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_category
     *
     * @mbg.generated
     */
    List<TActCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TActCategory record);
}