package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.TActLeave;
import java.util.List;

public interface TActLeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_leave
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_leave
     *
     * @mbg.generated
     */
    int insert(TActLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_leave
     *
     * @mbg.generated
     */
    TActLeave selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_leave
     *
     * @mbg.generated
     */
    List<TActLeave> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_act_leave
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TActLeave record);
}