package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.TDepartmentHeader;
import java.util.List;

public interface TDepartmentHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_header
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_header
     *
     * @mbg.generated
     */
    int insert(TDepartmentHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_header
     *
     * @mbg.generated
     */
    TDepartmentHeader selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_header
     *
     * @mbg.generated
     */
    List<TDepartmentHeader> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department_header
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDepartmentHeader record);
}