package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.TDictData;
import java.util.List;

public interface TDictDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_data
     *
     * @mbg.generated
     */
    int insert(TDictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_data
     *
     * @mbg.generated
     */
    TDictData selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_data
     *
     * @mbg.generated
     */
    List<TDictData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDictData record);
}