package com.lind.springboot.generate.dao;

import com.lind.springboot.generate.model.TSetting;
import java.util.List;

public interface TSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int insert(TSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    TSetting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    List<TSetting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSetting record);
}